business_task:
  description: >
    Conduct comprehensive research on news related to the business market, new business models, new products, and services. 
    You can use the internet to find relevant information and should seek news from reliable and respected sources. 
    Report only the facts, do not make assumptions or speculations. We are in the year {current_year}. 
    Adapt your research to the following context: {context}.
  expected_output: >
    A list of the main news stories and a one-paragraph summary for each news story.

tech_task:
  description: >
    Conduct comprehensive research on news related to the technology market, new technologies, new software, and services. 
    You can use the internet to find relevant information and should seek news from reliable and respected sources. 
    Report only the facts, do not make assumptions or speculations. We are in the year {current_year}. 
    Adapt your research to the following context: {context}
  expected_output: >
    A list of the main news stories and a one-paragraph summary for each news story.

management_task:
  description: >
    Conduct comprehensive research on news related to management models, techniques, and best practices. 
    You can use the internet to find relevant information and should seek news from reliable and respected sources. 
    Report only the facts, do not make assumptions or speculations. We are in the year {current_year}. 
    Adapt your research to the following context: {context}.
  expected_output: >
    A list of the main news stories and a one-paragraph summary for each news story.

kg_task:
  description: >
    Read and analyze the content prepared by market research, technology research, and management research agents. The primary responsibility is to identify non-obvious connections between these different contents and generate a knowledge graph that explores up to three levels of depth in the connections.

    Task:
    - Receive and review the research conducted by the market, technology, and management research agents.
    - Identify and map non-obvious connections between the different studies.
    - Organize these connections into a knowledge graph, exploring up to three levels of depth in the implications.
    - We are in the year {current_year}.
    - Adapt your analysis to the following context: {context}
  expected_output: >
    The output should be only the graph in Mermaid format, without any additional information.

report_task:
  description: >
    Read the knowledge graph generated by the Research Connections Analyst and, from it, identify and generate actionable business insights. These insights should be objective, clear, and relevant, allowing executives to discuss and adapt their business strategies in a practical and efficient manner.

    Task:
    - Receive and review the knowledge graph generated by the Research Connections Analyst.
    - Interpret the connections and patterns identified in the graph, extracting relevant information.
    - Generate actionable and objective business insights, focusing on practical strategies and necessary adaptations to prepare the organization for emerging changes.
    - Ensure that the insights are presented clearly and without futurism, focusing on concrete actions that executives can discuss and implement.
    - We are in the year {current_year}.
    - Adapt your analysis to the following context: {context}
  expected_output: >
    List of actionable business insights, presented in a clear and objective text format, structured for easy understanding and discussion by executives.
    Example:
    1. **Insight 1:** Increase in demand for sustainable technology solutions
      - **Action:** Invest in research and development of eco-friendly products
      - **Impact:** Market positioning as a leader in sustainability
      - **Timeline:** 6-12 months

    2. **Insight 2:** Growing need for AI training within IT teams
      - **Action:** Implement AI training programs for IT employees
      - **Impact:** Improvement in operational efficiency and technological innovation
      - **Timeline:** 3-6 months
